version: '3.9'

services:
  web:
    build: .
    command: gunicorn grinatom.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/grinatom/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  sqlite_data:
    driver: local
